### ISSUE TITLE
Not Properly Aligned

### ISSUE THREAD

**Issue by willysr** [kylehuff/webpg-firefox#8]
Hi, i'm using Slackware-Current and Firefox (20) and latest code from github
It worked nicely here, but when i tried to send signed or encrypted message, the verify and/or decrypt process because the text wasn't properly aligned

Here's the screenshot prior sending the signed text and after it has been loaded by GMail
![test-sign](https://f.cloud.github.com/assets/240100/463183/d79353cc-b530-11e2-9586-057cad577ce6.jpg)
![verify-failed](https://f.cloud.github.com/assets/240100/463184/f5df33aa-b530-11e2-9e9d-76fdb6622b66.jpg)

This happened when using new compose menu

**Comment by kylehuff** [comment]
Mr Raharjo,

It sounds to me that you are using the version from the Mozilla Addon site,
which is out-dated (mozilla is very slow to approve new versions), and
unfortunately there is an issue with the version due to a change in GMAIL;
The current version (v0.9.4) has resolved that issue (along with some other
issues).

Would you be willing to try the latest development cycle?
http://webpg.org/download/webpg-firefox/webpg-firefox-latest.xpi

It should resolve your issue, and I hope it will be available in the
Mozilla in the next few months.

Regards,
Kyle L. Huff
http://webpg.org/

**Comment by willysr** [comment]
> It sounds to me that you are using the version from the Mozilla Addon site,
> which is out-dated (mozilla is very slow to approve new versions), and
> unfortunately there is an issue with the version due to a change in GMAIL;
> The current version (v0.9.4) has resolved that issue (along with some other
> issues).
> 
> Would you be willing to try the latest development cycle?
> http://webpg.org/download/webpg-firefox/webpg-firefox-latest.xpi

Hi Kyle,

I'm building them from your github, so it contains the latest version

## 

Willy Sudiarto Raharjo
Personal Blog : http://willysr.blogspot.com
Linux Blog: http://slackblogs.blogspot.com

**Comment by kylehuff** [comment]
Oh, okay. In that case, would you by chance be using the "old compose"
interface in richtext mode? I believe there is still an issue with that
scenario, and being that the traditional compose window is being phased
out, I have not spent much time on it.

I hate to say "use plaintext" mode in the traditional composer, but I don't
have a good solution otherwise at this moment.

**Comment by willysr** [comment]
> Oh, okay. In that case, would you by chance be using the "old compose"
> interface in richtext mode? I believe there is still an issue with that
> scenario, and being that the traditional compose window is being phased
> out, I have not spent much time on it.
> 
> I hate to say "use plaintext" mode in the traditional composer, but I don't
> have a good solution otherwise at this moment.

No, i'm using plaintext mode only

## 

Willy Sudiarto Raharjo
Personal Blog : http://willysr.blogspot.com
Linux Blog: http://slackblogs.blogspot.com

**Comment by kylehuff** [comment]
In the old or new compose interface?

**Comment by willysr** [comment]
> In the old or new compose interface?

When i reported the bug, it was in the new compose
now, i'm switching to the old interface and use the package you sent
me, not by building it from github
the toolbar was broken in github, but it worked on your latest binary extension

## 

Willy Sudiarto Raharjo
Personal Blog : http://willysr.blogspot.com
Linux Blog: http://slackblogs.blogspot.com

**Comment by kylehuff** [comment]
I pushed a rather large commit a few hours ago, that XPI is built against
the latest commit...

Are you having issues with the compose formatting in the build I sent you?

**Comment by willysr** [comment]
> I pushed a rather large commit a few hours ago, that XPI is built against
> the latest commit...
> 
> Are you having issues with the compose formatting in the build I sent you?

I'm still testing it right now
it seems that if i had a signature with a URL like the one i used
below, it breaks the sign/encrypt process
i tried to remove them and finally i'm able to verify my own message
I'm not really sure if this is caused by gmail, GnuPG, or WebPG

i'll do more testing here

## 

Willy Sudiarto Raharjo
Personal Blog : http://willysr.blogspot.com
Linux Blog: http://slackblogs.blogspot.com

**Comment by kylehuff** [comment]
It is possible I broke something in one of my commits a few weeks ago. I
will do some testing tomorrow and see what I can find.

Thanks for letting me know about it, I will keep you posted on what I find,
if you don't find something first!

**Comment by willysr** [comment]
> It is possible I broke something in one of my commits a few weeks ago. I
> will do some testing tomorrow and see what I can find.
> 
> Thanks for letting me know about it, I will keep you posted on what I find,
> if you don't find something first!

Well, i do have one just now
the building key list is not working here, but it was working in git version
it just hung there without no output

for the meantime, i will change my signature in order to work with WebPG
i will also do more testing with the new compose interface

Thank you for creating this extension.

## 

Willy Sudiarto Raharjo

**Comment by willysr** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> for the meantime, i will change my signature in order to work with WebPG
> i will also do more testing with the new compose interface

Composing new message on the new compose interface does work with
WebPG after altering my signature and the webPG icon showed up as well

i guess you can close this issue, but the key building issue remains
with the pre-compiled packages, not with github version

---

Willy Sudiarto Raharjo
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.19 (GNU/Linux)

iEYEARECAAYFAlGF244ACgkQiHuDdNczM4F1bQCePrCCPvZcOHlP+SHzFg6tmPh5
iPQAmwcXI5ZSybg6WkX4EjXt8Sd/+Msg
=B1aJ
-----END PGP SIGNATURE-----

**Comment by willysr** [comment]
> > for the meantime, i will change my signature in order to work with WebPG
> > i will also do more testing with the new compose interface
> 
> Composing new message on the new compose interface does work with
> WebPG after altering my signature and the webPG icon showed up as well
> 
> i guess you can close this issue, but the key building issue remains
> with the pre-compiled packages, not with github version
> 
> Hmm... I think it's too early to say it's solved
> Replying break the verification process once again
> Probably due to < and > character

## 

Willy Sudiarto Raharjo

**Comment by willysr** [comment]
Here's another result of testing

Your binary package both on Firefox and Chrome (latest version)
New Compose Interface
UTF-8 charset
Using URL in the signature caused the rendering failed due to some addition on the URL links

1st screenshot: sending them on Chrome
![test-sign](https://f.cloud.github.com/assets/240100/463704/ee546748-b591-11e2-9778-420166ed4f45.jpg)

2nd screenshot: failed verifying on Firefox
![verify-failed](https://f.cloud.github.com/assets/240100/463705/ef00faf8-b591-11e2-98ef-801d55eee5fb.jpg)

3rd screenshot: original message displayed on Firefox
![original-message](https://f.cloud.github.com/assets/240100/463706/2eae91e2-b592-11e2-9360-643a4797df33.jpg)

**Comment by kylehuff** [comment]
On 05/05/2013 10:44 AM, Willy Sudiarto Raharjo wrote:

> Here's another result of testing
> 
> Your binary package both on Firefox and Chrome (latest version)
> New Compose Interface
> UTF-8 charset
> Using URL in the signature caused the rendering failed due to some 
> addition on the URL links
> 
> 1st screenshot: sending them on Chrome
> test-sign 
> https://f.cloud.github.com/assets/240100/463704/ee546748-b591-11e2-9778-420166ed4f45.jpg
> 
> 2nd screenshot: failed verifying on Firefox
> verify-failed 
> https://f.cloud.github.com/assets/240100/463705/ef00faf8-b591-11e2-98ef-801d55eee5fb.jpg
> 
> 3rd screenshot: original message displayed on Firefox
> original-message 
> https://f.cloud.github.com/assets/240100/463706/2eae91e2-b592-11e2-9360-643a4797df33.jpg
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/kylehuff/webpg-firefox/issues/8#issuecomment-17452708.

Yes, I have been doing some testing and found an issue where the 
"linkification" is causing problems because it happens twice. (GMAIL 
automatically converts links without HREF tags into links with HREF 
tags, so the message must be "linkified" before signing).

In any event, I believe I found issue(s) and will be pushing up a 
possible fix in a little bit.

**Comment by willysr** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Yes, I have been doing some testing and found an issue where the
> "linkification" is causing problems because it happens twice. (GMAIL
> automatically converts links without HREF tags into links with HREF
> tags, so the message must be "linkified" before signing).
> 
> In any event, I believe I found issue(s) and will be pushing up a
> possible fix in a little bit.

I do have another suggestion
as you can see from my screenshot, my signature is INLINE with the last message
is it possible to add a break (new line) for the signature before the
sign/encrypt process so that the signature is on a different line
rather than being inline with the message?

Thanks

---

Willy Sudiarto Raharjo

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.19 (GNU/Linux)

iEYEARECAAYFAlGGck0ACgkQiHuDdNczM4HhhwCeOowslOKk7DSy3kMk4K/O9zEH
GqAAnR+AUWFrqJD0q4xvIzSlVBc9mgyU
=HcOs
-----END PGP SIGNATURE-----

**Comment by willysr** [comment]
Another problem with default charset

Here's a screenshot from the same message, but probably interpreted differently

1st screenshot: the original message viewed by GMail in Firefox (default was set to UTF-8 in Settings)
![replying-original](https://f.cloud.github.com/assets/240100/463727/75eae1c6-b594-11e2-9667-0e4b96ced515.jpg)

2nd screenshot: the original message when using Show Original from GMail
![show-original](https://f.cloud.github.com/assets/240100/463714/fb374a78-b593-11e2-8cdb-5beef8e6dabe.jpg)

Kinda strange, since actually Google is able to detect them properly, but why do they present it differently on the browser

**Comment by willysr** [comment]
sorry, wrong screenshot, updated post

**Comment by kylehuff** [comment]
As I saying, GMAIL adds HTML tags to any links without valid A tags, when sending and when viewing. WebPG adds A tags to links without them, but in the case above, the formatting is not preserved when displaying the message, so GMAIL is adding additional A tags. I believe the issue to be fixed, I am just testing any impact it may have with parsing in other viewers (not GMAIL).

**Comment by kylehuff** [comment]
Okay, I just pushed up changes that should improve the gmail parsing, could you try it out and let me know?

**Comment by willysr** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> Okay, I just pushed up changes that should improve the gmail parsing, could you try it out and let me know?Unfortunately, the problem still persist when i opened up blogger.com (taking 100% CPU time)the script hung at line 176if (!webpg.inline.render_toolbar) {and line 236return (node.parentNode.nodeName.indexOf(acceptNode) == -1);

i will test the parsing in firefox and chrome shortly
- --Willy Sudiarto Raharjo
  -----BEGIN PGP SIGNATURE-----
  Version: GnuPG v2.0.19 (GNU/Linux)

iEYEARECAAYFAlGGiUUACgkQiHuDdNczM4GT8QCfQKQeXFrGC42PQyGsV73tPMaP
lNMAn3osRwhwaHPUQfeIn+WRPTty8CtX
=AIhn
-----END PGP SIGNATURE-----

**Comment by willysr** [comment]
Sending thorugh Firefox/Chrome is now OK
Replying by including original message without expanding the quoted message in new compose editor works perfectly

however, when replying by expanding the original message and edit them (leaving only the important part) breaks the verification process

**Comment by willysr** [comment]
i will consider this issue is closed
